/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.AdminBaseDatos;
import Modelo.Cliente;
import Modelo.Validaciones;
import java.awt.Color;
import java.awt.event.ActionListener;
import java.text.ParseException;
import java.util.ArrayList;
import javax.swing.DefaultCellEditor;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author Michelt
 */
public class FrmTablaMorosos extends javax.swing.JFrame {

    private AdminBaseDatos conexion;
    private DefaultTableModel modelo;
    private FrmMenu frmMenu;
    private Validaciones validaciones;
    private ArrayList <Cliente> morosos;
    /**
     * Creates new form FrmTablaMorosos
     */
    public FrmTablaMorosos(AdminBaseDatos conexion, FrmMenu frmMenu) throws ParseException {
        initComponents();
        this.conexion=conexion;
        this.frmMenu = frmMenu;
        this.validaciones= new Validaciones();
        this.morosos = conexion.getClientes();
        
        JTextField tf = new JTextField();
        tf.setEditable(false);
        DefaultCellEditor editor = new DefaultCellEditor( tf );
        tblMorosos.setDefaultEditor(Object.class, editor);
        
        ArrayList<Cliente> morosos2 = new ArrayList<>();
        for(Cliente cliente : morosos){
            if (validaciones.calcularDiasRestantes(cliente.getFechaSigPago()) == -1){
                morosos2.add(cliente);
            }
        }
        
        this.setTablaMorosos(morosos2);
        tblMorosos.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        JTableHeader header = tblMorosos.getTableHeader();
        header.setBackground(Color.red);
        this.modelo = (DefaultTableModel) tblMorosos.getModel();
        
    }
    
    public void escuchar(ActionListener manejador){
         this.btnSalir.addActionListener(manejador);
    
    }
    
    public void setTablaMorosos(ArrayList<Cliente> clientes) throws ParseException{
        DefaultTableModel modelo = (DefaultTableModel) this.tblMorosos.getModel();
       for(Cliente cliente: clientes){
           int diasRestantes = validaciones.calcularDiasRestantes(cliente.getFechaSigPago());
           String fechaProxPago = validaciones.generarFechaProxPago(cliente.getFechaPago());
           if(validaciones.calcularMorosos(cliente.getFechaPago())){
                Object[] tmp={cliente.getIdCliente(),diasRestantes,cliente.getNombreCliente(),cliente.getPrimerApellido(),cliente.getSegundoApellido(),
                cliente.getCedula(),cliente.getTelefono(),cliente.getDireccion(),cliente.getEmail(),cliente.getFechaIngreso(),
                cliente.getFechaPago(),fechaProxPago,cliente.getMorosidades(),cliente.getComentarios(),cliente.isTratoEspecial()};
                modelo.addRow(tmp);
           }
       }
    
    }

    public ArrayList<Cliente> getMorosos() {
        return morosos;
    }

    public void setMorosos(ArrayList<Cliente> morosos) {
        this.morosos = morosos;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblMorosos = new javax.swing.JTable();
        btnSalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tabla de morosos");

        tblMorosos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Clientes", "Días restantes para vencimiento", "Nombre", "Primer Apellido", "Segundo Apellido", "Cedula", "Telefono", "Dirección", "E-mail", "Fecha de Ingreso", "Fecha de Pago", "Fecha del próximo pago", "Morosidades", "Comentarios", "Trato Especial"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblMorosos.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblMorosos);
        if (tblMorosos.getColumnModel().getColumnCount() > 0) {
            tblMorosos.getColumnModel().getColumn(0).setPreferredWidth(100);
            tblMorosos.getColumnModel().getColumn(1).setPreferredWidth(120);
            tblMorosos.getColumnModel().getColumn(2).setPreferredWidth(100);
            tblMorosos.getColumnModel().getColumn(3).setPreferredWidth(120);
            tblMorosos.getColumnModel().getColumn(4).setPreferredWidth(110);
            tblMorosos.getColumnModel().getColumn(5).setPreferredWidth(110);
            tblMorosos.getColumnModel().getColumn(6).setPreferredWidth(110);
            tblMorosos.getColumnModel().getColumn(7).setPreferredWidth(330);
            tblMorosos.getColumnModel().getColumn(8).setPreferredWidth(140);
            tblMorosos.getColumnModel().getColumn(9).setPreferredWidth(120);
            tblMorosos.getColumnModel().getColumn(10).setPreferredWidth(120);
            tblMorosos.getColumnModel().getColumn(11).setPreferredWidth(120);
            tblMorosos.getColumnModel().getColumn(12).setPreferredWidth(150);
            tblMorosos.getColumnModel().getColumn(13).setPreferredWidth(200);
            tblMorosos.getColumnModel().getColumn(14).setPreferredWidth(100);
        }

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Avisos de Pago del Día");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 981, Short.MAX_VALUE))
                .addGap(31, 31, 31))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
                .addGap(34, 34, 34)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblMorosos;
    // End of variables declaration//GEN-END:variables
}
